### ISSUE TITLE
[question] why is library built before running tests?

### ISSUE THREAD

**Issue by itaditya** [FlowAppPlatform/flow-sdk#15]
Since, the tests import the source files from `src/` directory, why is the library built?

**Comment by nawazdhandala** [comment]
We test if the library builds properly and build stage does not fail

**Comment by itaditya** [comment]
Ohh that's nice. In that case, I think **building** should be the last step then. When we make some changes in code, most of the time it should build but there is a higher chance that unit test fails and I think getting the result is more important while developing. After the tests run successfully, we can see if build is also proper. Let me know your thoughts

**Comment by nawazdhandala** [comment]
Sure. We can do that,.
